version: '3.7'
services:
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  sw-api:
    build: .
    restart: always
    container_name: sw-api
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"